name: Generate Snake

on:
  schedule:
    # Executes every 12 hours
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DeepakDeepak0
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the updated snake.svg to the output branch
      - name: Push generated snake
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
