name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: DeepakDeepak0
          outputs: |
            ./output/snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Snake animation"
          add: "output/snake.svg"
