name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # daily at 12AM UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run Script
        run: |
          node fetch-leetcode-stats.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add leetcode-stats.md
          git commit -m "♻️ Update LeetCode stats" || echo "No changes"
          git push
